<h1> Data Analysis with python </h1>

In [12]:
import pandas as pd

In [13]:
# Read the CNH file
CNH = pd.read_excel("C:\\Users\\steve rufin\\Desktop\\Niagara_Revenue.xlsx")

In [14]:

# Display the CNH DataFrame
CNH

,Arrival Date,Arrival Day,WE indicator,Capacity,Days Out,Sys Rem Dem,Rem Dem STLY,Applied Rem Dem,User Override,Event,...,Room Collection 3 Rem Dem TY %,Room Collection 3 Rem Dem STLY #,Room Collection 3 Rem Dem STLY %,Room Collection 4 Hurdle Revenue,Room Collection 4 Transient OTB TY,Room Collection 4 Transient OTB STLY,Room Collection 4 Rem DemTY #,Room Collection 4 Rem Dem TY %,Room Collection 4 Rem Dem STLY #,Room Collection 4 Rem Dem STLY %
0,2020-06-01,MON,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.00,2,NaN,NaN,NaN,NaN,NaN
1,2020-06-02,TUE,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.00,5,NaN,NaN,NaN,NaN,NaN
2,2020-06-03,WED,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.00,4,NaN,NaN,NaN,NaN,NaN
3,2020-06-04,THU,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.00,6,NaN,NaN,NaN,NaN,NaN
4,2020-06-05,FRI,Y,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.00,8,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,2021-06-08,TUE,N,432,361,103.13,18.0,103.13,N,N,...,42.27,11.00,61.00,243.60,0,NaN,7.99,7.75,NaN,NaN
373,2021-06-09,WED,N,432,362,107.72,26.0,107.72,N,N,...,41.57,16.00,62.00,243.60,0,NaN,8.13,7.54,2.00,8.0
374,2021-06-10,THU,N,432,363,108.94,490.8,108.94,N,N,...,38.83,220.91,45.01,154.92,0,NaN,7.94,7.29,38.29,7.8
375,2021-06-11,FRI,Y,432,364,509.76,NaN,509.76,N,N,...,44.68,NaN,NaN,240.47,0,NaN,35.43,6.95,NaN,NaN
376,2021-06-12,SAT,Y,432,365,455.60,NaN,455.60,N,N,...,41.51,NaN,NaN,150.97,0,NaN,30.83,6.77,NaN,NaN

In [5]:
# Make a copy of CNH
df = CNH.copy()

In [42]:
# Display df
df.head()

,Arrival Date,Arrival Day,WE indicator,Capacity,Days Out,Sys Rem Dem,Rem Dem STLY,Applied Rem Dem,User Override,Event,...,Room Collection 3 Rem Dem TY %,Room Collection 3 Rem Dem STLY #,Room Collection 3 Rem Dem STLY %,Room Collection 4 Hurdle Revenue,Room Collection 4 Transient OTB TY,Room Collection 4 Transient OTB STLY,Room Collection 4 Rem DemTY #,Room Collection 4 Rem Dem TY %,Room Collection 4 Rem Dem STLY #,Room Collection 4 Rem Dem STLY %
0,2020-06-01,MON,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,2,NaN,NaN,NaN,NaN,NaN
1,2020-06-02,TUE,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,5,NaN,NaN,NaN,NaN,NaN
2,2020-06-03,WED,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,4,NaN,NaN,NaN,NaN,NaN
3,2020-06-04,THU,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,6,NaN,NaN,NaN,NaN,NaN
4,2020-06-05,FRI,Y,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,8,NaN,NaN,NaN,NaN,NaN

<h3> Exploratory analysis </h3>

In [7]:
# describe df
df.describe()

,Capacity,Sys Rem Dem,Rem Dem STLY,Applied Rem Dem,Total Available Transient Supply,Total Transient Booked,Total Transient Booked STLY,Additional Demand,Additional Demand STLY,Total Transient Demand,...,Room Collection 3 Rem Dem TY %,Room Collection 3 Rem Dem STLY #,Room Collection 3 Rem Dem STLY %,Room Collection 4 Hurdle Revenue,Room Collection 4 Transient OTB TY,Room Collection 4 Transient OTB STLY,Room Collection 4 Rem DemTY #,Room Collection 4 Rem Dem TY %,Room Collection 4 Rem Dem STLY #,Room Collection 4 Rem Dem STLY %
count,377.0,366.000000,364.000000,366.000000,377.000000,301.000000,338.000000,148.000000,338.000000,377.000000,...,366.000000,363.000000,363.000000,377.000000,377.000000,219.000000,366.000000,366.000000,356.000000,356.000000
mean,432.0,168.166885,211.058077,163.475574,395.264960,22.016611,90.748521,19.990608,21.480030,184.131592,...,36.811202,79.638099,38.945730,4.322149,1.501326,7.301370,10.430437,6.785437,16.735197,9.489775
std,0.0,125.139357,157.277895,118.867674,42.579159,20.904299,120.876345,17.375392,41.603572,125.946725,...,7.874366,61.443453,9.802116,29.841123,2.253985,8.590081,7.423298,2.862946,13.024180,7.466831
min,432.0,17.850000,0.260000,17.850000,186.860000,1.000000,1.000000,0.230000,0.000000,32.640000,...,15.130000,1.000000,6.000000,0.000000,0.000000,1.000000,1.040000,2.800000,0.260000,1.000000
25%,432.0,62.542500,62.550000,62.542500,380.040000,3.000000,5.000000,8.152500,0.000000,78.600000,...,31.545000,25.140000,33.340000,0.000000,0.000000,1.000000,4.032500,5.522500,5.412500,6.000000
50%,432.0,105.205000,193.105000,106.515000,407.000000,13.000000,15.000000,15.760000,0.445000,135.450000,...,37.415000,64.910000,38.000000,0.000000,0.000000,4.000000,7.575000,6.275000,13.340000,7.850000
75%,432.0,280.860000,357.235000,271.000000,429.820000,40.000000,144.750000,27.487500,23.877500,298.920000,...,41.215000,130.545000,43.000000,0.000000,3.000000,10.000000,17.592500,7.042500,25.942500,10.477500
max,432.0,509.760000,569.880000,521.000000,432.320000,103.000000,438.000000,88.730000,262.160000,534.000000,...,72.030000,241.910000,81.000000,243.600000,20.000000,48.000000,35.430000,22.120000,62.880000,100.000000

In [10]:
# display the first 5 rows of df
df.head()

,Arrival Date,Arrival Day,WE indicator,Capacity,Days Out,Sys Rem Dem,Rem Dem STLY,Applied Rem Dem,User Override,Event,...,Room Collection 3 Rem Dem TY %,Room Collection 3 Rem Dem STLY #,Room Collection 3 Rem Dem STLY %,Room Collection 4 Hurdle Revenue,Room Collection 4 Transient OTB TY,Room Collection 4 Transient OTB STLY,Room Collection 4 Rem DemTY #,Room Collection 4 Rem Dem TY %,Room Collection 4 Rem Dem STLY #,Room Collection 4 Rem Dem STLY %
0,2020-06-01,MON,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,2,NaN,NaN,NaN,NaN,NaN
1,2020-06-02,TUE,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,5,NaN,NaN,NaN,NaN,NaN
2,2020-06-03,WED,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,4,NaN,NaN,NaN,NaN,NaN
3,2020-06-04,THU,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,6,NaN,NaN,NaN,NaN,NaN
4,2020-06-05,FRI,Y,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,NaN,0.0,8,NaN,NaN,NaN,NaN,NaN

In [11]:
# Display the last 5 rows of df
df.tail()

,Arrival Date,Arrival Day,WE indicator,Capacity,Days Out,Sys Rem Dem,Rem Dem STLY,Applied Rem Dem,User Override,Event,...,Room Collection 3 Rem Dem TY %,Room Collection 3 Rem Dem STLY #,Room Collection 3 Rem Dem STLY %,Room Collection 4 Hurdle Revenue,Room Collection 4 Transient OTB TY,Room Collection 4 Transient OTB STLY,Room Collection 4 Rem DemTY #,Room Collection 4 Rem Dem TY %,Room Collection 4 Rem Dem STLY #,Room Collection 4 Rem Dem STLY %
372,2021-06-08,TUE,N,432,361,103.13,18.0,103.13,N,N,...,42.27,11.00,61.00,243.60,0,NaN,7.99,7.75,NaN,NaN
373,2021-06-09,WED,N,432,362,107.72,26.0,107.72,N,N,...,41.57,16.00,62.00,243.60,0,NaN,8.13,7.54,2.00,8.0
374,2021-06-10,THU,N,432,363,108.94,490.8,108.94,N,N,...,38.83,220.91,45.01,154.92,0,NaN,7.94,7.29,38.29,7.8
375,2021-06-11,FRI,Y,432,364,509.76,NaN,509.76,N,N,...,44.68,NaN,NaN,240.47,0,NaN,35.43,6.95,NaN,NaN
376,2021-06-12,SAT,Y,432,365,455.60,NaN,455.60,N,N,...,41.51,NaN,NaN,150.97,0,NaN,30.83,6.77,NaN,NaN

<h3> Data transformation

In [48]:
# Convert the 'Arrival Date' Series to a Datetime data type
df['Arrival Date'] = pd.to_datetime(df['Arrival Date'])

In [47]:
df['Arrival Date']

0     2020-06-01
1     2020-06-02
2     2020-06-03
3     2020-06-04
4     2020-06-05
         ...
372   2021-06-08
373   2021-06-09
374   2021-06-10
375   2021-06-11
376   2021-06-12
Name: Arrival Date, Length: 377, dtype: datetime64[ns]

In [61]:
# Change the 'Capacity' to integer data type
df['Capacity']=df['Capacity'].astype(int)

In [69]:
# Display all the columns available in my df 
myCol = list(df)

<h5> What is for each Arrival Date to sum all of Rooms Collection Revenue, Total Available Transient Supply, Total Transient Demand?

In [83]:
# Set the option to display all the rows in the DataFrame
pd.set_option('display.max_rows', None)

In [125]:
# Adding the 'Sum All Rooms Collection Hurdle Revenue' Series to df
df['Sum All Rooms Collection Hurdle Revenue'] = df['Room Collection 1 Hurdle Revenue'] + df['Room Collection 2 Hurdle Revenue'] + df['Room Collection 3 Hurdle Revenue'] +df['Room Collection 4 Hurdle Revenue']

In [128]:
# Checking that the newly created Column has been added
df.shape

(377, 105)

In [131]:
display("The new df has 105 columns, which is one more that the previous")

'The new df has 105 columns, which is one more that the previous'

In [129]:
# Display the first 2 rows of the new df
df.head(2)

,Arrival Date,Arrival Day,WE indicator,Capacity,Days Out,Sys Rem Dem,Rem Dem STLY,Applied Rem Dem,User Override,Event,...,Room Collection 3 Rem Dem STLY #,Room Collection 3 Rem Dem STLY %,Room Collection 4 Hurdle Revenue,Room Collection 4 Transient OTB TY,Room Collection 4 Transient OTB STLY,Room Collection 4 Rem DemTY #,Room Collection 4 Rem Dem TY %,Room Collection 4 Rem Dem STLY #,Room Collection 4 Rem Dem STLY %,Sum All Rooms Collection Hurdle Revenue
0,2020-06-01,MON,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,0.0,2,NaN,NaN,NaN,NaN,NaN,0.0
1,2020-06-02,TUE,N,432,Actual,NaN,NaN,NaN,Y,N,...,NaN,NaN,0.0,5,NaN,NaN,NaN,NaN,NaN,0.0

In [130]:
display("The final result that answers the question is below")
df[['Arrival Date','Sum All Rooms Collection Hurdle Revenue','Total Available Transient Supply','Total Transient Demand']]

'The final result that answers the question is below'

,Arrival Date,Sum All Rooms Collection Hurdle Revenue,Total Available Transient Supply,Total Transient Demand
0,2020-06-01,0.00,395.74,63.74
1,2020-06-02,0.00,406.66,72.74
2,2020-06-03,0.00,401.86,45.83
3,2020-06-04,0.00,400.46,55.57
4,2020-06-05,0.00,379.70,75.26
5,2020-06-06,0.00,312.71,117.44
6,2020-06-07,0.00,376.55,78.60
7,2020-06-08,0.00,412.51,69.74
8,2020-06-09,0.00,409.43,54.73
9,2020-06-10,0.00,390.79,42.10
10,2020-06-11,0.00,406.92,45.87
11,2020-06-12,0.00,389.34,114.04
12,2020-06-13,0.00,375.54,113.74
13,2020-06-14,0.00,418.20,83.49
14,2020-06-15,0.00,424.67,126.67
15,2020-06-16,0.00,422.38,118.67
16,2020-06-17,0.00,420.72,124.60
17,2020-06-18,0.00,417.95,99.08
18,2020-06-19,0.00,393.27,165.92
19,2020-06-20,0.00,398.99,139.94
20,2020-06-21,0.00,418.36,105.88
21,2020-06-22,0.00,418.90,121.03
22,2020-06-23,0.00,418.04,115.78
23,2020-06-24,0.00,422.34,103.24
24,2020-06-25,0.00,413.90,136.41
25,2020-06-26,0.00,413.70,172.95
26,2020-06-27,0.00,428.04,183.80
27,2020-06-28,0.00,428.60,155.94
28,2020-06-29,0.00,429.76,142.60
29,2020-06-30,0.00,429.82,161.25
30,2020-07-01,0.00,431.23,307.98
31,2020-07-02,0.00,430.10,121.45
32,2020-07-03,0.00,428.97,188.59
33,2020-07-04,0.00,427.00,416.71
34,2020-07-05,0.00,430.56,118.66
35,2020-07-06,0.00,429.85,120.85
36,2020-07-07,0.00,429.54,118.02
37,2020-07-08,0.00,430.95,115.97
38,2020-07-09,0.00,431.60,122.69
39,2020-07-10,0.00,430.65,123.02
40,2020-07-11,0.00,430.95,125.49
41,2020-07-12,0.00,430.40,139.99
42,2020-07-13,0.00,430.67,141.78
43,2020-07-14,0.00,430.92,146.00
44,2020-07-15,0.00,431.17,145.45
45,2020-07-16,0.00,431.48,127.87
46,2020-07-17,0.00,430.68,132.55
47,2020-07-18,0.00,430.37,154.24
48,2020-07-19,0.00,429.56,117.90
49,2020-07-20,0.00,430.64,138.28
50,2020-07-21,0.00,412.57,120.01
51,2020-07-22,0.00,411.86,110.14
52,2020-07-23,0.00,419.30,130.78
53,2020-07-24,0.00,421.76,137.60
54,2020-07-25,0.00,420.63,161.86
55,2020-07-26,0.00,429.81,131.85
56,2020-07-27,0.00,429.94,140.52
57,2020-07-28,0.00,430.80,119.11
58,2020-07-29,0.00,431.73,87.49
59,2020-07-30,0.00,432.22,116.67
60,2020-07-31,0.00,432.11,136.66
61,2020-08-01,0.00,429.88,120.03
62,2020-08-02,0.00,424.91,129.45
63,2020-08-03,0.00,429.23,146.08
64,2020-08-04,0.00,429.98,145.99
65,2020-08-05,0.00,431.90,110.50
66,2020-08-06,0.00,421.02,140.08
67,2020-08-07,0.00,417.66,146.60
68,2020-08-08,0.00,417.23,140.55
69,2020-08-09,0.00,430.77,129.99
70,2020-08-10,0.00,430.94,431.98
71,2020-08-11,0.00,430.99,436.75
72,2020-08-12,0.00,431.14,356.53
73,2020-08-13,0.00,431.70,448.75
74,2020-08-14,0.00,431.07,454.57
75,2020-08-15,0.00,431.46,439.53
76,2020-08-16,0.00,431.56,442.13
77,2020-08-17,0.00,431.66,448.27
78,2020-08-18,0.00,425.60,441.33
79,2020-08-19,0.00,425.78,360.45
80,2020-08-20,0.00,431.20,430.37
81,2020-08-21,0.00,431.24,354.62
82,2020-08-22,0.00,431.75,339.55
83,2020-08-23,0.00,431.31,431.28
84,2020-08-24,0.00,431.44,430.83
85,2020-08-25,0.00,431.39,434.01
86,2020-08-26,0.00,431.56,422.56
87,2020-08-27,0.00,431.30,426.20
88,2020-08-28,0.00,431.12,365.20
89,2020-08-29,0.00,430.92,371.48
90,2020-08-30,0.00,430.47,435.15
91,2020-08-31,0.00,431.29,439.75
92,2020-09-01,0.00,431.59,412.35
93,2020-09-02,0.00,430.86,393.64
94,2020-09-03,0.00,431.23,395.88
95,2020-09-04,0.00,431.41,323.02
96,2020-09-05,0.00,419.23,308.07
97,2020-09-06,0.00,430.64,432.64
98,2020-09-07,0.00,426.53,411.22
99,2020-09-08,0.00,383.79,394.64
100,2020-09-09,0.00,416.21,453.99
101,2020-09-10,0.00,409.18,441.81
102,2020-09-11,0.00,409.60,385.83
103,2020-09-12,0.00,415.19,383.96
104,2020-09-13,0.00,407.54,407.74
105,2020-09-14,0.00,410.08,372.59
106,2020-09-15,0.00,406.79,335.68
107,2020-09-16,0.00,405.97,355.29
108,2020-09-17,0.00,424.91,366.14
109,2020-09-18,0.00,425.02,373.85
110,2020-09-19,0.00,395.42,385.91
111,2020-09-20,0.00,405.72,390.25
112,2020-09-21,0.00,342.74,335.56
113,2020-09-22,0.00,256.68,166.16
114,2020-09-23,0.00,186.86,170.36
115,2020-09-24,0.00,234.93,237.21
116,2020-09-25,0.00,391.17,315.70
117,2020-09-26,0.00,407.90,394.60
118,2020-09-27,0.00,377.43,328.33
119,2020-09-28,0.00,395.61,300.34
120,2020-09-29,0.00,343.55,298.92
121,2020-09-30,0.00,431.41,314.36
122,2020-10-01,0.00,424.41,356.01
123,2020-10-02,0.00,384.40,363.10
124,2020-10-03,0.00,422.21,350.22
125,2020-10-04,0.00,356.59,333.47
126,2020-10-05,0.00,312.50,303.93
127,2020-10-06,0.00,325.74,315.92
128,2020-10-07,0.00,336.85,307.68
129,2020-10-08,0.00,385.11,336.46
130,2020-10-09,0.00,384.91,334.08
131,2020-10-10,0.00,404.79,375.00
132,2020-10-11,0.00,396.58,338.66
133,2020-10-12,0.00,408.72,304.21
134,2020-10-13,0.00,344.63,322.10
135,2020-10-14,0.00,342.03,301.51
136,2020-10-15,0.00,361.17,270.12
137,2020-10-16,0.00,349.73,328.43
138,2020-10-17,0.00,374.53,300.00
139,2020-10-18,0.00,383.13,289.76
140,2020-10-19,0.00,386.16,275.75
141,2020-10-20,0.00,386.40,276.57
142,2020-10-21,0.00,397.31,256.00
143,2020-10-22,0.00,397.29,337.73
144,2020-10-23,0.00,397.27,355.28
145,2020-10-24,0.00,406.91,351.30
146,2020-10-25,0.00,406.46,277.42
147,2020-10-26,0.00,372.35,275.21
148,2020-10-27,0.00,337.21,237.15
149,2020-10-28,0.00,336.60,229.37
150,2020-10-29,0.00,372.42,257.45
151,2020-10-30,0.00,407.39,297.08
152,2020-10-31,0.00,432.20,358.00
153,2020-11-01,0.00,432.05,213.83
154,2020-11-02,0.00,432.03,144.91
155,2020-11-03,0.00,432.05,156.53
156,2020-11-04,0.00,432.18,153.98
157,2020-11-05,0.00,384.26,213.58
158,2020-11-06,0.00,412.16,229.77
159,2020-11-07,0.00,412.24,287.84
160,2020-11-08,0.00,432.10,156.68
161,2020-11-09,0.00,431.10,100.76
162,2020-11-10,0.00,431.11,117.06
163,2020-11-11,0.00,431.26,99.09
164,2020-11-12,0.00,432.32,131.08
165,2020-11-13,0.00,416.33,309.33
166,2020-11-14,0.00,327.16,307.01
167,2020-11-15,0.00,432.10,197.44
168,2020-11-16,0.00,432.04,118.36
169,2020-11-17,0.00,432.22,128.57
170,2020-11-18,0.00,432.19,119.69
171,2020-11-19,0.00,432.07,167.83
172,2020-11-20,0.00,432.11,333.59
173,2020-11-21,0.00,432.10,302.00
174,2020-11-22,0.00,432.04,177.64
175,2020-11-23,0.00,432.09,117.05
176,2020-11-24,0.00,432.07,122.90
177,2020-11-25,0.00,432.26,159.61
178,2020-11-26,0.00,431.42,248.95
179,2020-11-27,0.00,431.44,347.51
180,2020-11-28,0.00,431.25,366.35
181,2020-11-29,0.00,432.07,108.56
182,2020-11-30,0.00,432.04,89.99
183,2020-12-01,0.00,392.09,88.01
184,2020-12-02,0.00,402.12,100.02
185,2020-12-03,0.00,382.06,122.70
186,2020-12-04,0.00,342.05,242.54
187,2020-12-05,0.00,342.00,231.91
188,2020-12-06,0.00,402.00,84.32
189,2020-12-07,0.00,402.09,73.53
190,2020-12-08,0.00,402.13,52.29
191,2020-12-09,0.00,402.07,52.42
192,2020-12-10,0.00,382.03,110.02
193,2020-12-11,0.00,352.00,197.71
194,2020-12-12,0.00,352.09,224.82
195,2020-12-13,0.00,352.05,97.87
196,2020-12-14,0.00,352.06,73.44
197,2020-12-15,0.00,352.07,76.64
198,2020-12-16,0.00,412.02,80.42
199,2020-12-17,0.00,412.00,53.02
200,2020-12-18,0.00,352.04,184.02
201,2020-12-19,0.00,352.03,230.05
202,2020-12-20,0.00,412.05,101.13
203,2020-12-21,0.00,432.09,133.40
204,2020-12-22,0.00,432.10,206.37
205,2020-12-23,0.00,432.15,177.55
206,2020-12-24,0.00,432.11,230.11
207,2020-12-25,0.00,432.17,312.25
208,2020-12-26,0.00,432.13,364.66
209,2020-12-27,0.00,412.13,285.42
210,2020-12-28,0.00,402.21,300.40
211,2020-12-29,0.00,402.16,155.26
212,2020-12-30,0.00,422.18,269.98
213,2020-12-31,841.36,431.45,534.00
214,2021-01-01,0.00,431.44,301.59
215,2021-01-02,0.00,427.19,298.72
216,2021-01-03,0.00,427.03,165.29
217,2021-01-04,0.00,432.00,166.19
218,2021-01-05,0.00,432.00,146.40
219,2021-01-06,0.00,422.07,157.33
220,2021-01-07,0.00,402.03,158.53
221,2021-01-08,0.00,352.00,233.57
222,2021-01-09,0.00,377.00,265.23
223,2021-01-10,0.00,412.07,108.19
224,2021-01-11,0.00,387.14,135.45
225,2021-01-12,0.00,387.01,110.37
226,2021-01-13,0.00,397.00,101.36
227,2021-01-14,0.00,412.00,90.82
228,2021-01-15,0.00,417.07,199.02
229,2021-01-16,0.00,407.07,264.28
230,2021-01-17,0.00,392.03,84.37
231,2021-01-18,0.00,347.02,53.42
232,2021-01-19,0.00,372.00,40.07
233,2021-01-20,0.00,387.00,35.19
234,2021-01-21,0.00,397.12,59.65
235,2021-01-22,0.00,402.11,172.18
236,2021-01-23,0.00,402.06,249.15
237,2021-01-24,0.00,427.00,67.16
238,2021-01-25,0.00,327.00,46.93
239,2021-01-26,0.00,327.00,61.91
240,2021-01-27,0.00,327.00,61.25
241,2021-01-28,0.00,387.00,43.46
242,2021-01-29,0.00,427.00,158.19
243,2021-01-30,0.00,427.00,273.12
244,2021-01-31,0.00,407.00,68.39
245,2021-02-01,0.00,392.00,56.32
246,2021-02-02,0.00,407.00,46.45
247,2021-02-03,0.00,347.00,46.89
248,2021-02-04,0.00,342.00,47.97
249,2021-02-05,0.00,392.00,180.88
250,2021-02-06,0.00,422.00,286.60
251,2021-02-07,0.00,382.00,52.88
252,2021-02-08,0.00,367.00,44.59
253,2021-02-09,0.00,387.00,64.47
254,2021-02-10,0.00,407.00,67.61
255,2021-02-11,0.00,407.15,65.83
256,2021-02-12,0.00,432.21,291.00
257,2021-02-13,0.00,432.12,400.94
258,2021-02-14,0.00,432.08,214.50
259,2021-02-15,0.00,422.06,60.83
260,2021-02-16,0.00,402.04,70.27
261,2021-02-17,0.00,402.02,51.13
262,2021-02-18,0.00,417.00,84.06
263,2021-02-19,0.00,412.00,281.92
264,2021-02-20,0.00,415.00,353.96
265,2021-02-21,0.00,412.00,105.31
266,2021-02-22,0.00,397.00,74.27
267,2021-02-23,0.00,387.00,67.16
268,2021-02-24,0.00,397.00,61.82
269,2021-02-25,0.00,407.00,79.56
270,2021-02-26,0.00,372.00,238.64
271,2021-02-27,0.00,372.03,337.59
272,2021-02-28,0.00,377.00,101.55
273,2021-03-01,0.00,382.00,62.58
274,2021-03-02,0.00,357.03,65.19
275,2021-03-03,0.00,382.02,48.20
276,2021-03-04,0.00,412.03,98.40
277,2021-03-05,0.00,382.02,255.92
278,2021-03-06,0.00,397.05,287.40
279,2021-03-07,0.00,427.02,64.68
280,2021-03-08,0.00,407.04,60.20
281,2021-03-09,0.00,407.01,60.38
282,2021-03-10,0.00,417.00,60.51
283,2021-03-11,0.00,342.08,74.66
284,2021-03-12,0.00,377.05,165.85
285,2021-03-13,0.00,412.10,249.34
286,2021-03-14,0.00,387.02,107.10
287,2021-03-15,0.00,387.05,99.42
288,2021-03-16,0.00,357.03,74.74
289,2021-03-17,0.00,362.00,63.28
290,2021-03-18,0.00,372.00,67.31
291,2021-03-19,0.00,357.07,102.16
292,2021-03-20,0.00,397.05,124.97
293,2021-03-21,0.00,397.01,47.90
294,2021-03-22,0.00,387.00,45.96
295,2021-03-23,0.00,387.03,52.27
296,2021-03-24,0.00,392.00,47.70
297,2021-03-25,0.00,372.00,43.11
298,2021-03-26,0.00,412.04,87.52
299,2021-03-27,0.00,412.02,112.97
300,2021-03-28,0.00,402.02,44.68
301,2021-03-29,0.00,387.05,42.04
302,2021-03-30,0.00,402.05,32.71
303,2021-03-31,0.00,407.02,38.37
304,2021-04-01,0.00,382.04,32.64
305,2021-04-02,0.00,432.06,255.57
306,2021-04-03,0.00,432.10,251.47
307,2021-04-04,0.00,432.05,207.01
308,2021-04-05,0.00,422.04,39.00
309,2021-04-06,0.00,347.01,37.53
310,2021-04-07,0.00,342.06,36.58
311,2021-04-08,0.00,311.29,45.86
312,2021-04-09,732.95,212.22,303.41
313,2021-04-10,769.88,212.10,307.34
314,2021-04-11,3.68,380.04,141.41
315,2021-04-12,0.00,367.02,49.52
316,2021-04-13,0.00,352.01,44.22
317,2021-04-14,0.00,347.05,43.68
318,2021-04-15,0.00,362.07,46.06
319,2021-04-16,0.00,387.02,64.72
320,2021-04-17,0.00,407.00,64.57
321,2021-04-18,0.00,422.00,33.25
322,2021-04-19,0.00,417.00,55.59
323,2021-04-20,0.00,387.06,55.45
324,2021-04-21,0.00,377.04,35.45
325,2021-04-22,0.00,382.10,79.42
326,2021-04-23,0.00,392.05,82.19
327,2021-04-24,0.00,407.02,90.65
328,2021-04-25,0.00,412.00,58.87
329,2021-04-26,0.00,402.00,70.39
330,2021-04-27,0.00,392.06,71.91
331,2021-04-28,0.00,352.02,74.44
332,2021-04-29,0.00,357.00,79.87
333,2021-04-30,0.00,362.07,94.28
334,2021-05-01,0.00,380.02,91.89
335,2021-05-02,0.00,342.03,60.43
336,2021-05-03,0.00,317.05,63.54
337,2021-05-04,0.00,302.04,69.22
338,2021-05-05,0.00,342.04,63.67
339,2021-05-06,0.00,347.06,69.73
340,2021-05-07,0.00,392.21,105.92
341,2021-05-08,0.00,402.04,106.08
342,2021-05-09,0.00,417.02,55.18
343,2021-05-10,0.00,337.02,49.51
344,2021-05-11,0.00,348.03,61.71
345,2021-05-12,0.00,389.00,57.31
346,2021-05-13,0.00,344.04,59.84
347,2021-05-14,0.00,344.02,105.95
348,2021-05-15,0.00,344.07,121.38
349,2021-05-16,0.00,417.03,79.56
350,2021-05-17,0.00,402.06,46.84
351,2021-05-18,0.00,347.04,57.39
352,2021-05-19,0.00,352.02,60.11
353,2021-05-20,0.00,372.00,57.07
354,2021-05-21,0.00,407.00,303.55
355,2021-05-22,0.00,418.00,355.90
356,2021-05-23,0.00,372.00,345.80
357,2021-05-24,0.00,358.00,69.72
358,2021-05-25,0.00,295.03,80.93
359,2021-05-26,0.00,267.02,81.80
360,2021-05-27,0.00,322.00,80.45
361,2021-05-28,0.00,412.00,350.93
362,2021-05-29,0.00,430.00,418.67
363,2021-05-30,0.00,416.00,359.95
364,2021-05-31,0.00,361.00,91.87
365,2021-06-01,0.00,299.00,94.05
366,2021-06-02,0.00,335.00,94.34
367,2021-06-03,0.00,349.00,113.41
368,2021-06-04,0.00,387.00,140.78
369,2021-06-05,0.00,397.00,174.09
370,2021-06-06,0.00,390.00,132.21
371,2021-06-07,0.00,205.00,101.86
372,2021-06-08,974.40,190.00,103.13
373,2021-06-09,945.49,190.00,107.72
374,2021-06-10,856.50,345.00,108.94
375,2021-06-11,859.40,387.00,509.76
376,2021-06-12,603.88,413.00,455.60